### ISSUE TITLE
Six digits of precision after decimal place

### ISSUE THREAD

**Issue by chadpod** [michaeleisel/JJLISO8601DateFormatter#1]
The formatter seems to be failing (returns nil) with dates like this:

2018-08-17T02:14:02.662762Z

This is with these format options:

NSISO8601DateFormatWithFullDate | NSISO8601DateFormatWithFullTime | NSISO8601DateFormatWithFractionalSeconds;

The same options used with NSDateFormatter parse the string correctly.

Any ideas? Thanks for developing the library!

**Comment by michaeleisel** [comment]
Fixed by 6f70d7d8b452ab06f36e300f511a8da70f192245 and included in version 0.1.1

Let me know if you still see issues, thank you for reporting this!

**Comment by chadpod** [comment]
Thanks Michael!
