### ISSUE TITLE
TARGET_OS_SIMULATOR and TARGET_OS_OSX not defined when building Xcode 12.5 for iOS 14.5 beta

### ISSUE THREAD

**Issue by kevinbhayes** [michaeleisel/JJLISO8601DateFormatter#2]
When including ZippyJSON in my project (SwiftPM), building passes using Xcode 12.4 building for iOS 14.4. But when building in Xcode 12.5 for iOS 14.4 I get two build errors when building JJLISO8601DateFormatter:

…/SourcePackages/checkouts/JJLISO8601DateFormatter/Sources/JJLISO8601DateFormatter/Vendor/tzdb/tzfile__.h:27:6: 'TARGET_OS_SIMULATOR' is not defined, evaluates to 0

and 

…/SourcePackages/checkouts/JJLISO8601DateFormatter/Sources/JJLISO8601DateFormatter/Vendor/tzdb/tzfile__.h:27:30: 'TARGET_OS_OSX' is not defined, evaluates to 0

**Comment by kevinbhayes** [comment]
Note, this can be fixed by including

```
#include <TargetConditionals.h>
```

in `tzfile__.h`

**Comment by michaeleisel** [comment]
done in 0.1.4, which zippyjson uses in 1.2.4
