### ISSUE TITLE
Fatal error when building on linux

### ISSUE THREAD

**Issue by RandomHashTags** [michaeleisel/JJLISO8601DateFormatter#4]
### Device
- architecture: x86_64
- os: Arch Linux
- kernel: 6.2.9-arch1-1
- packages: 575

### Software
- Swift 5.8-RELEASE
- using the Swift Package Manager (for ZippyJSON)

### Description
I don't use this library, but I do use ZippyJSON. It compiles just fine on macOS, Xcode 14.3. The exact error is:
```
In file included from /<path>/.build/checkouts/JJLISO8601DateFormatter/Sources/JJLISO8601DateFormatter/JJLISO8601DateFormatter.m:3: /<path>/.build/checkouts/JJLISO8601DateFormatter/Sources/JJLISO8601DateFormatter/include/JJLISO8601DateFormatter.h:3:9: fatal error: 'Foundation/Foundation.h' file not found

#import <Foundation/Foundation>
        ^~~~~~~~~~~~~~~~~~~~~~~

1 error generated.

/<path>/.build/checkouts/JJLISO8601DateFormatter/Sources/JJLISO8601DateFormatter/JJInternal.c:7:9: fatal error: 'CoreFoundation/CFDateFormatter.h' file not found

#import <CoreFoundation/CFDateFormatter.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by michaeleisel** [comment]
Linux isn't supported

**Comment by RandomHashTags** [comment]
Understandable, however, it was working just fine on Linux before Swift 5.8 was released.

======================
UPDATE Apr 8, 13:20 CDT, 2023

It never worked on linux. Only work-around is to switch from Obj-C to C/Swift/C++. Time to reinvent the wheel.

**Comment by michaeleisel** [comment]
It's nice to hear that it works in some cases, but whether it works in some or none, there won't be any work from my end on supporting it. I'm ok to review/merge a PR though if you see a simple fix

**Comment by RandomHashTags** [comment]
The only fix I am able to find right now is to convert all Objective-C code to C/Swift. I don't know the methodology behind using Obj-C here, but would you still merge a PR like this? Otherwise my other option is to create a fork of ZippyJSON without this package.

**Comment by michaeleisel** [comment]
I would not, and I'm not sure why moving to Swift 5.8 would have a problem where there wasn't one already. ZippyJSON, too, isn't supported for Linux. If I were you and still pursuing this though, the fork of ZippyJSON w/o the package is what I would do
