### ISSUE TITLE
Compiling error with Xcode 16

### ISSUE THREAD

**Issue by we7ee** [michaeleisel/JJLISO8601DateFormatter#7]
I use ZippyJSON as cocoapod and when I'm trying to run my Project with Xcode 16 I recieve following error in the `tzfile_`:

`Missing '#include <sys/_types/_ssize_t.h>'; 'ssize_t' must be declared before it is used`

<img width="1056" alt="Screenshot 2024-06-12 at 08 50 51" src="https://github.com/michaeleisel/JJLISO8601DateFormatter/assets/8250493/14945e53-dfd6-4e49-b76b-b758cac66d37">

**Comment by michaeleisel** [comment]
Things have been fixed now. Please wait a couple hours for the update to propagate on cocoapods servers and then update and let me know if it works
